# Funding Configuration for MikroTik Auto Backup Tool

# GitHub Sponsors
github: [yourusername]

# Other funding platforms
# Patreon
patreon: yourusername

# Open Collective
open_collective: mikrotik-backup-tool

# Ko-fi
ko_fi: yourusername

# Tidelift
tidelift: pypi/mikrotik-backup-tool

# Buy Me a Coffee
buy_me_a_coffee: yourusername

# Custom funding
custom: ["https://www.paypal.com/donate/?hosted_button_id=yourpaypal"]
